### ISSUE TITLE
The conda.compat module is deprecated

### ISSUE THREAD

**Issue by cclauss** [kangwonlee/travis-yml-conda-posix-nt#7]
https://travis-ci.org/kangwonlee/travis-yml-conda-posix-nt/jobs/516500387#L459

WARNING: The conda.compat module is deprecated and will be removed in a future release.

**Comment by kangwonlee** [comment]
* This message seems based on https://github.com/conda/conda/issues/7078
* [A google search](https://superuser.com/questions/1422008/conda-install-packagename-gives-deprecation-warning) implies no need to worry about for now

**Comment by cclauss** [comment]
I avoid building new things on functionality that is already deprecated.  Using __conda create —yes__ seems a better solution.

**Comment by kangwonlee** [comment]
* Thanks for your opinion.
* IMHO, I would like to understand the role of the [`conda.compat`](https://github.com/conda/conda/blob/master/conda/compat.py) and/or [`conda.common.compat`](https://github.com/conda/conda/blob/master/conda/common/compat.py) modules; so that I could make correct decisions.
* Or, at least why the message appeared in the log.

**Comment by mh-lan** [comment]
Yes and even I run `conda install`, this warning appears. That worries me alot.

**Comment by cclauss** [comment]
What __conda install__ command causes the depreciation warning to appear?

**Comment by mh-lan** [comment]
Almost any modules.  I verified `conda install matplotlib`, and it returns warning message
**WARNING: The conda.compat module is deprecated and will be removed in a future release.**

**Comment by kangwonlee** [comment]
* I made one of compat.py files in conda 4.6.11 to raise `DeprecationWarning` (Windows version)
* Following could be a sample of a part of the message 

``` 
$ conda update conda

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\Users\user_id_here\Anaconda3\lib\site-packages\conda\exceptions.py", line 1003, in __call__
        return func(*args, **kwargs)
      File "C:\Users\user_id_here\Anaconda3\lib\site-packages\conda\cli\main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "C:\Users\user_id_here\Anaconda3\lib\site-packages\conda\cli\conda_argparse.py", line 80, in do_call
        module = import_module(relative_mod, __name__.rsplit('.', 1)[0])
      File "C:\Users\user_id_here\Anaconda3\lib\importlib\__init__.py", line 127, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
      File "<frozen importlib._bootstrap>", line 983, in _find_and_load
      File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 728, in exec_module
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "C:\Users\user_id_here\Anaconda3\lib\site-packages\conda\cli\main_update.py", line 8, in <module>
        from .install import install
      File "C:\Users\user_id_here\Anaconda3\lib\site-packages\conda\cli\install.py", line 18, in <module>
        from ..core.index import calculate_channel_urls, get_index
      File "C:\Users\user_id_here\Anaconda3\lib\site-packages\conda\core\index.py", line 10, in <module>
        from .package_cache_data import PackageCacheData
      File "C:\Users\user_id_here\Anaconda3\lib\site-packages\conda\core\package_cache_data.py", line 15, in <module>
        from .path_actions import CacheUrlAction, ExtractPackageAction
      File "C:\Users\user_id_here\Anaconda3\lib\site-packages\conda\core\path_actions.py", line 13, in <module>
        from .envs_manager import get_user_environments_txt_file, register_env, unregister_env
      File "C:\Users\user_id_here\Anaconda3\lib\site-packages\conda\core\envs_manager.py", line 11, in <module>
        from .prefix_data import PrefixData
      File "C:\Users\user_id_here\Anaconda3\lib\site-packages\conda\core\prefix_data.py", line 23, in <module>
        from ..gateways.disk.create import write_as_json_to_file
      File "C:\Users\user_id_here\Anaconda3\lib\site-packages\conda\gateways\disk\create.py", line 22, in <module>
        from ...cli.python_api import run_command, Commands  # noqa
      File "C:\Users\user_id_here\Anaconda3\lib\site-packages\conda\cli\python_api.py", line 9, in <module>
        from ..compat import encode_arguments
      File "C:\Users\user_id_here\Anaconda3\lib\site-packages\conda\compat.py", line 69, in <module>
        raise DeprecationWarning
    DeprecationWarning

```

**Comment by kangwonlee** [comment]
* According to https://github.com/conda/conda/issues/7078, following modules could be deprecated in the future?<br> `conda.cli.activate`<br> `conda.compat`<br> `conda.install`

* Also according to https://github.com/conda/conda/issues/8512, IMHO, they are working on it so let's see for now?
* Or manually applying https://github.com/conda/conda/pull/8507/commits/35a04674fffc9fd85ce0e5ed5c25281a32ac7f04 could be helpful?<br>In my case, the location of the file seems to be `Anaconda3/pkgs/conda-4.6.11-py37_0/Lib/site-packages/conda/cli/python_api.py`

* To be honest, I have not completely understood the role of the `compat.py` yet; its docstring says it is like `six.py`.

**Comment by kangwonlee** [comment]
* Another issue I sort of noticed regarding `pip` is the package version control
* Another [google search](https://stackoverflow.com/questions/5226311/installing-specific-package-versions-with-pip) implies that using `pip`, specifying the package version seems not straight forward

**Comment by kangwonlee** [comment]
* I thought so but the same google search includes following grammar

``` sh
pip install 'matplotlib>=2.0.0,<3.0.0' --force-reinstall
```

* It was available in the [pip documentation](https://pip.pypa.io/en/stable/user_guide/#installing-packages) too

**Comment by kangwonlee** [comment]
* Planning to work on a Travis-CI recipe using `pip` on [a different repository](https://github.com/kangwonlee/momisp).
